spring:
  cloud:
    function:
      definition: messageProcessor
    stream:
      kafka:
        binder:
          transaction:
            transaction-id-prefix: tx-
          configuration:
            isolation.level: read_committed
            retries: 1
            acks: all
            processing.guarantee: exactly_once
      bindings:
        messageProcessor-in-0:
          consumer:
            maxAttempts: 3
          destination: person-topic
          content-type: application/json
          group: consumidorPerson
        messageProcessor-out-0:
          destination: person-topic
          content-type: application/json

  application:
    name: cloud-stream
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/mydatabase
    hikari:
      maximum-pool-size: 15
      connection-timeout: 2000
      idle-timeout: 1000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers:
      - localhost:9092